# -*- coding: utf-8 -*-
"""topsis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9tZzXd_nHL7fQVTClnV3iMFt4gvbcvV
"""

import pandas as pd
import numpy as np
import csv
import sys

def main():
    if len(sys.argv) == 5:
        input_file = sys.argv[1]
        weights = sys.argv[2]
        impacts = sys.argv[3]
        result_file = sys.argv[4]
        topsis(input_file, weights, impacts, result_file)
    else:
        print("Usage: python <program.py> <InputDataFile> <Weights> <Impacts> <ResultFileName>")
        print("Example: $python topsis.py data.csv  “1,1,1,2”  “+,+,-,+”  output-result.csv")

def topsis(input_file, weights, impacts, result_file):
    try:
        # ---------- Read File ----------
        df = pd.read_csv(input_file)

        # ---------- Minimum Column Check ----------
        if df.shape[1] < 3:
            raise ValueError("Input file must contain three or more columns.")

        # ---------- Parse Weights ----------
        try:
            weights = [float(w.strip()) for w in weights.split(',')]
        except:
            raise ValueError("Weights must be numeric and comma separated.")

        # ---------- Parse Impacts ----------
        impacts = [i.strip() for i in impacts.split(',')]
        for i in impacts:
            if i not in ['+', '-']:
                raise ValueError("Impacts must be either + or -.")

        # ---------- Criteria Count Validation ----------
        if len(weights) != len(df.columns) - 1 or len(impacts) != len(df.columns) - 1:
            raise ValueError("Number of weights, impacts, and criteria columns must be the same.")

        # ---------- Numeric Validation ----------
        try:
            data = df.iloc[:, 1:].astype(float)
        except:
            raise ValueError("Columns from 2nd to last must contain numeric values only.")

        # ---------- Normalization ----------
        norm_df = data / np.sqrt((data ** 2).sum())

        # ---------- Weighted Normalized Matrix ----------
        wt_norm_df = norm_df * weights

        # ---------- Ideal Best and Worst ----------
        ideal_pos = []
        ideal_neg = []

        for i in range(len(impacts)):
            if impacts[i] == '+':
                ideal_pos.append(wt_norm_df.iloc[:, i].max())
                ideal_neg.append(wt_norm_df.iloc[:, i].min())
            else:
                ideal_pos.append(wt_norm_df.iloc[:, i].min())
                ideal_neg.append(wt_norm_df.iloc[:, i].max())

        ideal_pos = np.array(ideal_pos)
        ideal_neg = np.array(ideal_neg)

        # ---------- Separation Measures ----------
        sep_pos = np.sqrt(((wt_norm_df - ideal_pos) ** 2).sum(axis=1))
        sep_neg = np.sqrt(((wt_norm_df - ideal_neg) ** 2).sum(axis=1))

        # ---------- TOPSIS Score ----------
        topsis_score = sep_neg / (sep_neg + sep_pos)

        # ---------- Ranking ----------
        rank = topsis_score.rank(ascending=False, method='dense').astype(int)

        # ---------- Result ----------
        result_df = pd.concat(
            [df, pd.DataFrame({'Topsis Score': topsis_score, 'Rank': rank})],
            axis=1
        )

        result_df.to_csv(result_file, index=False, quoting=csv.QUOTE_ALL, quotechar='"')
        print(f"TOPSIS completed successfully. Result saved to {result_file}")

    except FileNotFoundError:
        print(f"Error: File {input_file} not found.")
    except ValueError as e:
        print(f"Error: {str(e)}")
    except Exception as e:
        print(f"An unexpected error occurred: {str(e)}")

if __name__ == "__main__":
    main()